# Generated by Django 5.1.1 on 2024-10-16 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='course_enrolled',
        ),
    ]
