# Generated by Django 5.1.1 on 2024-10-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentinfo',
            name='Department',
        ),
        migrations.AddField(
            model_name='departmentinfo',
            name='name',
            field=models.CharField(default='CSE'),
        ),
    ]
