# Generated by Django 5.1 on 2024-11-12 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_studentinfo_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ta',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.studentinfo'),
        ),
    ]
