# Generated by Django 5.1.1 on 2024-10-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_studentinfo_course_enrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='course_enrolled',
            field=models.ManyToManyField(default='1', related_name='enrolled_students', to='userprofile.courseinfo'),
        ),
    ]
