# Generated by Django 5.1.1 on 2024-10-19 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_alter_studentinfo_course_enrolled'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(max_length=9)),
                ('Name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentInfo',
            fields=[
                ('department_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Department', models.CharField(choices=[('CSE', 'CSE'), ('CE', 'CE'), ('MOT', 'MOT')])),
            ],
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='N_id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='advisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advising_students', to='userprofile.admininfo'),
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='Department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='userprofile.departmentinfo'),
        ),
    ]
