# Generated by Django 5.1.1 on 2024-10-19 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_courseinfo_points_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='course_enrolled',
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='userprofile.courseinfo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='userprofile.studentinfo')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
