# Generated by Django 5.1.1 on 2024-11-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('course_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('school', models.CharField(choices=[('Tandon', 'Tandon'), ('Stern', 'Stern'), ('Tisch', 'Tisch'), ('Gallatin', 'Gallatin')], default='Tandon')),
                ('undergrad_capacity', models.IntegerField(blank=True)),
                ('grad_Capacity', models.IntegerField()),
                ('phd_course_capacity', models.IntegerField()),
                ('class_days', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=100, null=True)),
                ('start_time', models.TimeField(blank=True, default='09:00:00')),
                ('end_time', models.TimeField(blank=True, default='09:00:00')),
                ('description', models.CharField(max_length=1000)),
                ('to_waitlist', models.BooleanField(blank=True, default=False)),
                ('points_assigned', models.IntegerField(blank=True, null=True)),
                ('credits', models.DecimalField(decimal_places=1, max_digits=3)),
                ('waitlist_capacity', models.IntegerField(default=35)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_assigned', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('is_waitlisted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
