# Generated by Django 5.1.1 on 2024-10-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('course_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('course_Capacity', models.IntegerField()),
                ('phd_course_capacity', models.IntegerField()),
                ('class_day', models.DateField()),
                ('class_time', models.TimeField()),
                ('description', models.CharField(max_length=1000)),
                ('points_assigned', models.CharField(max_length=3, null=True)),
                ('credits', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_assigned', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('is_waitlisted', models.BooleanField(default=False)),
            ],
        ),
    ]
