# Generated by Django 5.1.1 on 2024-11-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseEnroll', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinfo',
            name='class_day',
        ),
        migrations.RemoveField(
            model_name='courseinfo',
            name='class_time',
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='class_days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='end_time',
            field=models.TimeField(blank=True, default='09:00:00'),
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='start_time',
            field=models.TimeField(blank=True, default='09:00:00'),
        ),
    ]
