# Generated by Django 5.1.1 on 2024-10-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseEnroll', '0003_alter_courseinfo_points_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinfo',
            name='to_waitlist',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
