# Generated by Django 5.1.1 on 2024-11-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseEnroll', '0004_alter_courseinfo_class_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseinfo',
            old_name='course_Capacity',
            new_name='grad_Capacity',
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='undergrad_capacity',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
