# Generated by Django 5.1.1 on 2024-11-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseEnroll', '0005_rename_course_capacity_courseinfo_grad_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='points_assigned',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
    ]
