# Generated by Django 5.1.1 on 2024-11-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseEnroll', '0006_alter_courseinfo_points_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinfo',
            name='waitlist_capacity',
            field=models.IntegerField(default=35),
        ),
    ]
