# Generated by Django 5.1.1 on 2024-11-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseEnroll', '0008_enrollment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='points_assigned',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
