# Generated by Django 5.1.1 on 2024-11-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseEnroll', '0009_alter_courseinfo_points_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinfo',
            name='school',
            field=models.CharField(choices=[('Tandon', 'Tandon'), ('Stern', 'Stern'), ('Tisch', 'Tisch'), ('Gallatin', 'Gallatin')], default='Tandon'),
        ),
    ]
