# Generated by Django 5.1 on 2024-11-12 22:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseEnroll', '0010_courseinfo_school'),
        ('userprofile', '0003_alter_ta_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverrideForm',
            fields=[
                ('form_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('explanation', models.TextField()),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='override_forms', to='courseEnroll.courseinfo')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='override_forms', to='userprofile.departmentinfo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='override_forms', to='userprofile.studentinfo')),
            ],
        ),
    ]
